# Last updated on 
@US1538263
@2019.PI06
@2019.PI06.03
@releasePresent
@iterationPresent
Feature: US1538263 - Handle Roster Update Event --> Cancel Contract Line using PCP Reassignment info

  @TC743460
  @Manual
  @Functional
  Scenario: TC743460 - [RL0]
    # Scenario 1 - Cancel Contract Line using PCP reassignment info
    Given that a contract has been created in Exari and successfully installed into Optum's legacy systems
    And that contract has multiple product groups
    When an "Update Roster" transaction is generated by Exari that includes a Provider Cancel
    And an Optum service built to handle a "Roster Update" event is started
    Then the service retrieves the Contract's configuration from the CMD service and stores that information in the OCM
    And the service retrieves the providers to cancel from Exari and stores that information in the OCM
    And the OCM is updated with "Need to Cancel Contract Line" for every qualified product group / provider combo that is a PCP with reassignment info
    And the OCM is updated with "Need to Cancel Contract Line" for every qualified product group / provider combo that is NOT a PCP
    # Are these two needed for just a happy path scenario??
    # And the service publishes an Kafka event to proceed with this 'Roster Update' transaction
    # And the service publishes the Kafka event with OCM data as previously described

