//import courgette.api.CourgetteOptions;
//import courgette.api.CourgetteRunLevel;
//import courgette.api.junit.Courgette;
//import cucumber.api.CucumberOptions;
//import org.junit.runner.RunWith;
//
///**
// * DO NOT EDIT THIS FILE.
// * Do not use this file to run tests. This framework is designed to be run using gradle, which manages all the dependencies.
// * <p>
// * Instead, execute tests using the following command:
// * <p>
// * ./gradlew parallelTest -Dcucumber.tags="@tags and @moreTags" -Dcourgette.threads=100
// */
//
//@RunWith(Courgette.class)
//@CourgetteOptions(
//        threads = 1,
//        // SCENARIO run level has shown to run faster than FEATURE
//        runLevel = CourgetteRunLevel.SCENARIO,
//        rerunFailedScenarios = false,
//        rerunAttempts = 1,
//        showTestOutput = true,
//        reportTargetDir = "build",
//        cucumberOptions = @CucumberOptions(
//                features = "src/test/resources/features",
//                plugin = {
//                        "pretty",
//                        "json:build/json-reports/json-report.json",
//                        "junit:build/xml-reports/xml-report.xml"},
//                glue = {"general_test", "rest_api_test", "ui_test", "exari_test"},
//                tags = {"@TC_CEN_SPGA_IN_05"},
//                strict = true
//        ))
//public class ParallelRunner {
//}