# Last updated on 
@US1410764
@2019.PI06
@2019.PI06.02
@releasePresent
@iterationPresent
Feature: US1410764 - Handle Roster Update Event --> Happy path (Compare Service)

  @TC737466
  @Manual
  @Functional
  Scenario: TC737466 - [RL0]
    Given the provider roster is updated
    When we add or cancel a provider corresponding to a contract
    Then provider roster needs to be updated with add or cancel provider
    #Api Semantecs:
    #Get (Contract ID)
    #Response:
    #{List <Provider, Action Type (add or cancel)>}

  @RC_unlinked
  @TC701599
  @Manual
  @Functional
  Scenario: TC701599 - [RL1]
    # Scenario 2 - Cancel Happy Path
    Given that a contract has been created in Exari and successfully installed into Optum's legacy systems
    And that contract has multiple product groups
    When an "Update Roster" transaction is generated by Exari that includes a Provider Cancel
    And an Optum service built to handle a "Roster Update" event is started
    Then the service retrieves the Contract's configuration from the CMD service and stores that information in the OCM
    And the service retrieves the providers to cancel from Exari and stores that information in the OCM
    And the OCM is updated with "N/A" for every non-qualified product group / provider combo
    # Are these two needed for just a happy path scenario??
    # And the service publishes an Kafka event to proceed with this 'Roster Update' transaction
    # And the service publishes the Kafka event with OCM data as previously described

